language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
- ./node_modules/.bin/testrpc
node_js:
- '4.2'
